# Generated by Django 3.2.5 on 2021-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210713_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(default=None, max_length=50, verbose_name="Book's name")),
                ('author', models.CharField(default=None, max_length=50, verbose_name="author's name")),
                ('isbn', models.IntegerField(default=0, verbose_name='ISBN')),
                ('pop', models.IntegerField(default=0, verbose_name='publication year')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
