# Generated by Django 2.2.5 on 2021-07-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210715_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.IntegerField(default=0, verbose_name='identification Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
