# Generated by Django 2.2.5 on 2021-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210715_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbook',
            name='returning',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='formbook',
            name='status',
            field=models.CharField(blank=True, choices=[('borrowed', 'borrowed'), ('available', 'available')], default='available', max_length=50, null=True),
        ),
    ]
