# Generated by Django 2.2.5 on 2021-07-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210716_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbook',
            name='returning',
            field=models.IntegerField(default=0, verbose_name='borrowing period'),
        ),
    ]
